version: '2'
services:
  run:
    build: .
    volumes:
    - .:/usr/src/app
    - ./.m2-cache:/root/.m2
    env_file:
    - secrets.env
    - config.env
    environment:
    - GLOBAL_ARTIFACT_URL_BASE=https://artifact.eventdata.crossref.org
    - GLOBAL_EVENT_BUS_BASE=https://bus.eventdata.crossref.org
    - QUERY_PREFIX_WHITELIST_ARTIFACT_NAME=crossref-doi-prefix-list
    - QUERY_WHITELIST_ARTIFACT_NAME=crossref-sourcelist
    command: "lein repl"

